src/ServiceStack/NativeTypes/CSharp/CSharpGenerator.cs
Bug causing duplicate types due to not adding processed type to existingOps hashset.
=> Duplicate types from CSharpGenerator

src/ServiceStack/ServerEventsFeature.cs
MemoryServerEvents use lookup table for GetSubscription and
GetSubscriptionInfosByUserId instead of loop through all entities.
=> Use lookup table for GetSubscription and GetSubscriptionInfosByUserId

src/ServiceStack.Authentication.OAuth2/MicrosoftOAuth2Provider.cs, src/ServiceStack.Authentication.OAuth2/ServiceStack.Authentication.OAuth2.csproj
Note:
- Gender is always null even if defined online in Microsoft Account site 
- http://localhost:11001 cannot be used as RedirectURL, for testing you should use something like http://devmachine.local:11001/
=> Microsoft Account OAuth 2 Provider added.

src/ServiceStack.Client/ServerEventsClient.cs, tests/ServiceStack.WebHost.Endpoints.Tests/ServerEventTests.cs
In some situations, response buffering is enabled on a server, causing ServerEvent messages to not be fully transmitted to the client.  One workaround is to remove dynamic compression, at a potential cost to all other API calls on the site.  The other option, [outlined by mythz here](http://stackoverflow.com/questions/25960723/servicestack-sever-sent-events/25983774#25983774), is to write an amount of bogus `\n` chars to the output stream.  This alternative locks up the `ServiceStack.ServerEventsClient` when attempting to digest the `\n` chars.
I'm not entirely happy with the logic, but it passes the unit tests.
OnPublish = (res, msg) =>
{
res.OutputStream.Write("\n\n\n\n\n\n\n\n\n\n");
}
=> Allow multiple newlines to be published on ServerEvents and silently consumed by the C# ServerEventsClient.

tests/ServiceStack.RazorHostTests/CatchAll.cshtml, tests/ServiceStack.RazorHostTests/ServiceStack.RazorHostTests.csproj, tests/ServiceStack.RazorHostTests/_CatchAllPartial.cshtml
Add a breakpoint at [line 515](https://github.com/ServiceStack/ServiceStack/blob/master/src/ServiceStack.Razor/ViewPageBase.cs#L515) in `ViewPageBase.cs`
Browse to `localhost:59115/catchall`
`.Dispose()` is called for CatchAll and SimplyLayout, but not for CatchAllPartial
This causes leaked db connections which, over time, will end up exhausting the pool and crashing the site.
=> Add failing test for Db.Dispose() in a razor partial.

src/ServiceStack.Authentication.MongoDb/ServiceStack.Authentication.MongoDB.csproj, src/ServiceStack.Authentication.MongoDb/packages.config, src/ServiceStack.Authentication.NHibernate/packages.config, src/ServiceStack.Caching.AwsDynamoDb/packages.config, src/ServiceStack.Caching.AwsDynamoDbV2/DynamoDbCacheClient.cs, src/ServiceStack.Caching.AwsDynamoDbV2/Properties/AssemblyInfo.cs, src/ServiceStack.Caching.AwsDynamoDbV2/ServiceStack.Caching.AwsDynamoDbV2.csproj, src/ServiceStack.Caching.AwsDynamoDbV2/packages.config, src/ServiceStack.Caching.Azure/ServiceStack.Caching.Azure.csproj, src/ServiceStack.Caching.Azure/packages.config, src/ServiceStack.Caching.Memcached/ServiceStack.Caching.Memcached.csproj, src/ServiceStack.Caching.Memcached/packages.config, src/ServiceStack.MsgPack/ServiceStack.MsgPack.csproj, src/ServiceStack.MsgPack/packages.config, src/ServiceStack.sln, src/packages/repositories.config
Added new ServiceStack.Caching.AwsDynamoDbV2 project that uses version 2.0+ of the 3rd party dependency and locked the current ServiceStack.Caching.AwsDynamoDb library to use only NuGet packages version prior to 2.0. 
Updated several NuGet packages in other projects to the most recent version of their 3rd party dependencies.
=> Added SS.Caching.AwsDynamoDbV2 and update deps

src/ServiceStack.Authentication.OAuth2/FourSquareOAuth2Provider.cs, tests/ServiceStack.AuthWeb.Tests/AppHost.cs
Added missing profile image dimensions to the URL. Defaulted the dimensions to 64x64, but the developer can set them using oauth.FourSquare.ProfileImageWidth and oauth.FourSquare.ProfileImageHeight appsettings.
=> Fixed FourSquare OAuth2 Profile Image URL

src/ServiceStack/MiniProfiler/UI/includes.tmpl
@mythz This is a tweak to the profiler output that will show the parameter values used in a SQL statement.
The MiniProfiler was already capturing the bound parameter values, it just wasn't displaying them. So I added conditional block in the template that displays each parameter/value on a line below the command string.
As you can see from the included screenshot, the CSS styling is not right. It's leaving huge whitespace between each parameter.
I really don't like raising half a pull request, but my CSS skillz are just not up to par. So after struggling with CSS for an hour, I decided to raise the PR and maybe you or another SS dev can finish the styling part?
=> MiniProfiler: Show SQL parameter names, types, and values below the command string

src/ServiceStack/NativeTypes/VbNet/VbNetGenerator.cs
Fix in regards to [problem posted on ServiceStack forums](https://forums.servicestack.net/t/add-servicestack-reference-created-dtos-do-not-handle-properties-using-reserved-keywords-properly-in-vb-net/690).
=> Add "Operator" to escaped keywords for VbNet NativeTypes

src/ServiceStack.Authentication.RavenDb/RavenDbUserAuthRepository.cs
We just had a problem where a user named "user.name" was getting logged in as "user.name-special".
The problem is that the index used in raven to find the users matching a username or email analyses the username and email, and so it splits on some characters, including '-'.
Then the .Search method is used, which is used for full text search, where we want .Where, which is exact match.
This change fixes both issues.
=> Fix wrong query/index on RavenDbUserAuthRepository

src/ServiceStack/NativeTypes/VbNet/VbNetGenerator.cs
Found a case where we used a public property named "Class" in C#. NativeTypes generated DTOs for VB.NET are not valid due to the Class keyword not being escaped.
Corrected by adding the "Class" keyword to KeyWords hashset.
=> Add "Class" to escaped keywords for VbNetGenerator NativeTypes

src/ServiceStack.Authentication.NHibernate/NHibernateUserAuthRepository.cs
A fix was applied as in several cases, the use of "using" will bubble up and close the database session and for such, resulting on an System.ObjectDisposedException Exception "Session is closed!" while performing normal tasks.
=> Applied fix for Session issues

src/ServiceStack.Common/ServiceModel/Serialization/JsonDataContractSerializer.cs
NullRefException would occur when returning an HttpResult w/o an object.
=> Don't try to serialize null objects in JsonDataContractSerializer

src/ServiceStack/ServiceStackHost.cs
1) Add the service name to initialization-complete message. This helps analysis when multiple logs from different processes get merged into a single stream.
2) Examine the StartupErrors collection to determine if anything went wrong during initialization.
Log.Info => when we know no errors occurred
Log.Error => when we know at least one error occurred. Also log the entire StartUpErrors collection as JSON, to help guide post-mortem analysis.
=> Log when errors are detected during application initialization

src/ServiceStack.Server/AutoQueryFeature.cs
1) clear limits and order by - we want to calculate aggregates for hole result not just current page and Order By will just fail in MS SQL without Group By on same fields
2) generate default alias if non supplied - MS SQL returns empty name for aggregates without alias
Current tests does not fail because of SqLite, they may require adjustments.
=> Minor fixes in AutoQuery IncludeAggregates response filter.

src/ServiceStack.Client/ServiceClientBase.cs
I added the CustomMethodAsync<TResponse>(string httpVerb, string relativeOrAbsoluteUrl, object request) to the ServiceClientBase.
I did not take the risk to add it to IRestClientAsync because I have trouble to build/tests all the sln.
=> Add CustomMethodAsync overload with url parameter to ServiceClientBase

src/ServiceStack.Interfaces/Redis/IRedisClient.cs, src/ServiceStack.Interfaces/Redis/IRedisNativeClient.cs
Adds support for `count` parameter to [`SPOP`](http://redis.io/commands/spop) allowing multiple items to be removed from a set at random.
SPOP key [count]
With high level equivalent method `PopItemsFromSet`.
=> Redis SPOP with count (Updated interfaces for Redis)

src/ServiceStack.Caching.Memcached/MemcachedValueWrapper.cs
Setting null-value to ICacheClient caused NRE when using Memcached backend
=> avoid NRE when setting null value to cache

src/ServiceStack.Api.Swagger/SwaggerApiService.cs
The problem that I was having was that the ApiMemberAttribute down the object chain inside Employee would not be picked up by swagger, such as in the example situation below.
The changes committed here add the DataType from ApiMemberAttribute if it exists.
```C#
public class SaveEmployee : IReturn<SaveEmployeeResponse>
{
[ApiMember(IsRequired = true, ParameterType = "path", AllowMultiple = false, DataType = "int")]
public string id { get; set; }
[ApiMember(ParameterType = "body", IsRequired = true, AllowMultiple = false, DataType = "Employee")]
public Employee employee { get; set; }
}
public class Employee
{
[ApiMember(IsRequired = true, AllowMultiple = false, DataType = "int")]
public string id { get; set; }
}
```
=> Swagger ApiMemberAttribute DataType 

src/ServiceStack/FluentValidation/Internal/MessageFormatter.cs, src/ServiceStack/FluentValidation/Results/ValidationFailure.cs, src/ServiceStack/FluentValidation/ValidationException.cs, src/ServiceStack/FluentValidation/Validators/PropertyValidator.cs, src/ServiceStack/ValidationResultExtensions.cs, tests/ServiceStack.Common.Tests/FluentValidation/ErrorCodeTests.cs
Automatically fills Meta with PlaceholderValues if no CustomState
provided for the rule.
The PlaceholderValues is a dict used internally by FV to build
ErrorMessage
There is no need to use ``WithState`` for built-in validators
=> FluentValidation: auto-fill Meta with PlaceholderValues if no CustomState provided

src/ServiceStack.ServiceInterface/SessionExtensions.cs, tests/ServiceStack.Common.Tests/ServiceStack.Common.Tests.csproj, tests/ServiceStack.Common.Tests/SessionExtensionTests.cs
Merging v4 fix to the v3 branch for unfriendly url chars in the
sessionid.
=> Don't create SessionId's with Url unfriendly chars

src/ServiceStack/PostmanFeature.cs
From a support email, Postman expects the "responses" to be an empty array if empty, but never "null" or the import collection in the app will throw an error.
This prevents the responses property to be null and if empty, it will output an empty array instead.
=> Postman responses can't be null

src/ServiceStack.Client/Support/NetDeflateProvider.cs, src/ServiceStack.Client/Support/NetGZipProvider.cs, src/ServiceStack.Interfaces/Caching/IDeflateProvider.cs, src/ServiceStack.Interfaces/Caching/IGZipProvider.cs, src/ServiceStack/RequestExtensions.cs
Avoid storing the uncompressed response as a string in memory; serialize into a GZip/Deflate stream directly. We have implemented this in a custom service runner for very large responses (hundreds of MB uncompressed) that compress well for a much healthier memory footprint. 
Please let me know what you think. Thanks.
=> Propose serializing directly into compression stream when making compressed result

src/.vs/config/applicationhost.config, src/ServiceStack.Mvc/ServiceStackController.cs, src/ServiceStack/AspNet/ServiceStackPage.cs
As discussed [here](https://github.com/ServiceStack/Issues/issues/363)
=> Fixed bug regarding unauthorised errors returning 302 instead of 401 when HtmlRedirect is null

src/ServiceStack.Authentication.OAuth2/InstagramOAuth2Provider.cs
A recent change in Authenticate handled the return value of OnAuthenticated as the return value, but that behaviour was missing on this provider and broke a particular flow on our app.
A quick comparisson between the base provider and this one seemed to show that the only relevant difference could be handled by AuthClientFilter.
I'm not 100% sure on this, but thought it's easier to show the change this way.
=> Authenticate override for Instagram no longer needed

src/ServiceStack/LocalizedStrings.cs, src/ServiceStack/NativeTypes/CSharp/CSharpGenerator.cs, src/ServiceStack/NativeTypes/FSharp/FSharpGenerator.cs, src/ServiceStack/NativeTypes/Java/JavaGenerator.cs, src/ServiceStack/NativeTypes/Swift/SwiftGenerator.cs, src/ServiceStack/NativeTypes/TypeScript/TypeScriptGenerator.cs, src/ServiceStack/NativeTypes/VbNet/VbNetGenerator.cs
Added a `Tip` to generated native types to help devs with convention of overriding DTO options by removing comment prefix.
Idea from [SSVS raised issue](https://github.com/ServiceStack/ServiceStackVS/issues/21).
Thoughts?
=> Suggestion for generated help message

src/ServiceStack/NativeTypes/Kotlin/KotlinGenerator.cs
For null assignment. Only affects classes without ResponseStatus already declared in response and `AddResponseStatus: True` in options.
=> Change ResponseStatus type to ResponseStatus?

src/ServiceStack/Auth/AuthProvider.cs
public override bool IsAuthorized(IAuthSession session, IAuthTokens tokens, Authenticate request = null)
contains : return !StringExtensions.IsNullOrEmpty(session.UserAuthName);
(before in callstack)
So, we have to compare UserAuthName in this method, cause sometimes session.UserName is null.
=> session.UserName -> session.UserAuthName

src/ServiceStack/ServerEventsFeature.cs
Our SSE server had a bit of trouble lately. The week before, our server become exhausted around 2am NZ time every day. Here is detail of what happen.
Our instance: AWS 8 cores instance with enough ram.
We have average 25k ~ 30k subscriptions during off peak time.
*** Reason drive me to made those change: *** We have been keep creating perfview for our SSE server, what I have observed was high CPU usage during server restart. Which has higher number of subscription came back in. It is similar event as the peak time. The error client side get is 504 service not available, where server is s till functional.
From perfview, during server restart, highest server usage was on `Array.Copy` and ConcurrentDictionary's `TryGetValue`. Where they are all under Registry method.
Before 14th, server keep …
=> Use ConcurrentDictionary to store IEventSubscription instead of Array[]

src/ServiceStack.Client/Serialization/StringMapTypeDeserializer.cs, src/ServiceStack/ServiceStackHost.Runtime.cs, tests/ServiceStack.WebHost.Endpoints.Tests/CustomValidationErrorTests.cs
As details of the request binding error are now returned, I've extended this to return all binding errors, rather than just the first one. So if a field fails to bind the process continues to try to bind the other fields, rather than throwing. The end result is that all binding errors should be returned to the client in one go, which is particularly desirable if the errors are indicated to an interactive user for correction.
Related: https://forums.servicestack.net/t/different-binding-behavior-based-on-content-type/1681
=> Return all request binding errors with serialization exception

src/ServiceStack.Client/ServerEventsClient.cs, tests/ServiceStack.WebHost.Endpoints.Tests/ServerEventTests.cs
Currently when updating `Channels` of an SSE client, restarting didn't update the `EventStreamUri`. Test and fix in PR.
I could be missing the expected flow, but fix was due to use case of:
```` csharp
var channels = new string[] { "home" };
var client = ServerEventsClient(baseUrl,channels);
client.Start();
client.Channels = new string[] { "new-channel" };
client.Restart();
// Excepted client to be listening on updated channels only.
````
=> Fix SSE client restart

src/ServiceStack.Client/ServerEventsClient.cs
To support other IServiceClients that implement IHasCookieContainer, eg
JsonHttpClient.
=> Change cast of ServiceClient in SSE client

src/ServiceStack.HttpClient/JsonHttpClient.cs
Otherwise SetCookie null refs on `HttpClient.BaseAddress`.
=> Re-instantiate HttpClient instance after Clear

src/ServiceStack/Auth/FacebookAuthProvider.cs
With Graph API 2.0 Facebook has removed the "username" field from the user data as retrieved from "/me". The url facebook.com/id will redirect to facebook.com/username
https://developers.facebook.com/docs/apps/upgrading#upgrading_v2_0_graph_api
=> Updated username to reflect changes per FB Graph API

src/ServiceStack.Authentication.OAuth2/InstagramOAuth2Provider.cs
When you authenticate using Instagram, the profile image is not showing up. Fixing code so that the profileUrl field gets added to items collection thereby causing the image to show up.
=> Instagram profile image is empty

src/ServiceStack/Html/Minifiers.css.cs
The regular expression in the CSS minifiy doesn't work properly for newlines.
For instance,
```
#id
div.test
{
display: none;
}
```
gets minified to
```
#iddiv.test{display:none}
```
The whitespace is removed between the #id and div.
This regex
```
css = Regex.Replace(css, @"[\n\r]+\s*", String.Empty);
```
should replace to a single space instead.
The above then minifies to:
```
#id div.test{display:none}
```
=> Fix issue handling newline in CSS minifier

src/ServiceStack/NativeTypes/TypeScript/TypeScriptGenerator.cs
Classes declared outside of a namespace causing an NRE when trying to generate native types.
=> Fix NRE for TypeScript generation

src/ServiceStack.Client/AsyncUtils.cs, src/ServiceStack.Client/ServerEventsClient.cs, tests/ServiceStack.WebHost.Endpoints.Tests/ServerEventTests.cs
The initial buffer size is 8192, but only 2048 is used because of this mistake.
The error is not critical, but need to be fixed.
=> Fix hard-coded buffer size

src/ServiceStack.Common/Data/IHasDbConnection.cs, src/ServiceStack.Common/MiniProfiler/Data/ProfiledCommand.cs, src/ServiceStack.Common/MiniProfiler/Data/ProfiledDbTransaction.cs
It allows getting the real transaction from a ProfiledDbTransaction in client code without Reflection hacks.
If this is OK I'll send a PR in ServiceStack.OrmLite to implement this interface in OrmLiteConnection and OrmLiteTransaction, too.
=> Added public IHasDbTransaction interface similar to IHasDbConnection

src/ServiceStack/NativeTypes/TypeScript/TypeScriptGenerator.cs
Fixes for TypeScript generation:
- Order of base types causing issues if base class is declared after for TS 1.8
https://github.com/Microsoft/TypeScript/issues/4341
- `createResponse` generating invalid code for primitives, eg `return new string()`.
=> TypeScript generation fixes

src/ServiceStack/ContainerTypeExtensions.cs, src/ServiceStack/Funq/Container.Adapter.cs, tests/ServiceStack.ServiceHost.Tests/IoCTests.cs
Added overloads of `RegisterAutoWiredType`, `RegisterAutoWired`, `RegisterAutoWiredAs` and `RegisterAs` to take `name` parameter to register named instance.
=> Implemented named registration for various IoC container overloads

src/ServiceStack/ServiceHost/RestPath.cs, tests/ServiceStack.ServiceHost.Tests/RestPathTests.cs
The following error happens if a literal after a route wildcard is not lower case. I've changed these two sections to be case insensitive.
Example:  
Fails: /api/Sample/{Path*}/Literal
Success: /api/Sample/{Path*}/literal
Index was outside the bounds of the array.
at ServiceStack.ServiceHost.RestPath.CreateRequest(String pathInfo, Dictionary`2 queryStringAndFormData, Object fromInstance) in C:\Source\ServiceStack\src\ServiceStack\ServiceHost\RestPath.cs:line 429
at ServiceStack.WebHost.Endpoints.RestHandler.GetRequest(IHttpRequest httpReq, IRestPath restPath) in C:\Source\ServiceStack\src\ServiceStack\WebHost.Endpoints\RestHandler.cs:line 143
at ServiceStack.WebHost.Endpoints.RestHandler.ProcessRequest(IHttpRequest httpReq, IHttpResponse httpRes, String operationName) in …
=> Mixed case after wildcard path causes "Index was outside the bounds of the array." error

src/ServiceStack/js/ss-utils.js
Changed $(window).unload() to $(window).on("unload", ) for compatibility with jQuery 3.x (they've removed methods deprecated since 1.8): https://github.com/jquery/jquery/issues/2286
=> jQuery 3.x Compatibility

src/ServiceStack.Authentication.MongoDb/MongoDbAuthRepository.cs, src/ServiceStack.Authentication.MongoDb/ServiceStack.Authentication.MongoDB.csproj, src/ServiceStack.Authentication.MongoDb/packages.config, tests/RazorRockstars.Console.Files/RazorRockstars.Console.Files.csproj, tests/RazorRockstars.Console.Files/StatelessAuthTests.cs, tests/RazorRockstars.Console.Files/packages.config
MongoDb driver updated
IManageApiKey interface implemented
MongoDbAuthRepoStatelessAuthTests added to StatelessAuthTests. It requires a MongoDb Server on localhost.
=> MongoDBAuthRepository updated for MongoDB Driver 2.2.4 and ApiKey support.

src/ServiceStack/Auth/AuthenticateService.cs
This commit makes saving session with SessionExpiry when user authenticated second time while session is active. Possible IAuthProvider should have `SessionExpiry` property to access it without casting to abstract class. 
https://forums.servicestack.net/t/session-never-expires/2906
=> Fix auth session extends on second authentication

src/ServiceStack/NativeTypes/TypeScript/TypeScriptGenerator.cs
Added "number" to primitiveDefaultValues because:
1. AppendType calls options.ImplementsFn to get type info for generating the responseTypeExpression (`createResponse() { return x; }`).
2. ImplementsFn calls Type(...) to get the type name of the return object
3. `string Type(string type, string[] genericArgs)` returns from TypeAlias
When generating the type definition for IReturn<int> from the above workflow, the result was the following (invalid) syntax: `createResponse() { return new number(); }`
The result will now be this: `createResponse() { return 0; }`
=> Add number to primitiveDefaultValues

src/ServiceStack/Auth/CredentialsAuthProvider.cs
Im trying to persist an Cart Id (eCommerce platform) on user log-in.
The requirement is that the user keeps his cart when he logs in.
I save the cartId i the session when the user logs in.
But in my subclass of the CredentialsAuthProvider onAuthenticated the CartId is gone.
=> add overwriteable method on authProvider for session value persistance.

NuGet.Core/ServiceStack.Core/ServiceStack.Core.nuspec
When I run `dotnet restore` on **ServiceStack.Core**, I get the following warning:
_warn : Detected package downgrade: System.Threading.ThreadPool from 4.0.10 to 4.0.1_ 
So, this PR is to bump the version. I didn't investigate whether or not there was a reason for picking 4.0.1, but this was the only dependency throwing the warning, so I assumed it was a typo.
=> [netcore] System.Threading.ThreadPool package downgrade warning

src/ServiceStack.Wire/Properties/AssemblyInfo.cs, src/ServiceStack.Wire/ServiceStack.Wire.csproj, src/ServiceStack.Wire/WireExtensions.cs, src/ServiceStack.Wire/WireFormat.cs, src/ServiceStack.Wire/WireServiceClient.cs, src/ServiceStack.Wire/packages.config, src/ServiceStack.sln, src/ServiceStack/IPlugin.cs, tests/RazorRockstars.Console.Files/MsgPackServiceTests.cs, tests/RazorRockstars.Console.Files/RazorRockstars.Console.Files.csproj, tests/RazorRockstars.Console.Files/packages.config, tests/ServiceStack.Common.Tests/FormatTests.cs, tests/ServiceStack.Common.Tests/ServiceStack.Common.Tests.csproj
Adding new format "wire". a fast Binary serializer for POCO objects
https://github.com/AsynkronIT/Wire
I am using the most tolerant Versioned mode which from the docs says
"Versioned, in this mode, Wire will emit both type names and field information in the output stream. This allows systems to have slightly different versions of the contract types where some fields may have been added or removed."
In this mode is isn't required to register the types for serializing in advance as it will as stated above emit the type and field info to the output stream so AFAIK you do not need to hold a dictionary of types as MsgPackFormat does.
I am also not sure of the lifecycle of serialization sessions so am using a single static instance of the serializer in the client.
=> Non-session optimized implementation of wire serializer

src/ServiceStack/ServiceStackHost.cs
I would like to make the container getter extensible in the appHost.
I was overwriting all the resolve, tryResolve, register, etc methods to add to the child container after startup. But Sometimes some code references to the AppHost.Container directly. Since this method is public why not make it overrideable. then with one override i can solve all my problems.
Usecase: Supply a childContainer (to plugins) per request or per customer  (depending on performance/memory usage)
=> Make the container behaviour in AppHost extensible

tests/ServiceStack.Common.Tests/ServiceStack.Common.Tests.csproj
when i restore packages and try to build it throws an error it cant find this dll.
apparently it downloaded another version of the dll.
=> Fix build error referencing wrong dll version dynamo.dll

src/ServiceStack/Host/ServiceController.cs
Since `IAppHost` directly references to `ServiceController` instead of `IServiceController` for whatever reason I do not know? (Either extend the interface or remove it completly imo).
Usecase:
It like to add some fallback strategy for when Service cannot be found.
Btw i cant build the project because pfx key file is missing, and when i remove it it dies on DynamoDbv2/CodeAnalysis.dll is missing  (nuget package version wanted 2.3.1.5.3, though version 2.3.3.0 was installed)
=> Making ServiceController extensible.

src/ServiceStack.Api.Swagger/swagger-ui-bootstrap/swagger-like-template.html
Added a "Required" column to the Parameters table.
Removed the "Required" column from the Response Model table.
The logic was simply in the wrong place.
Before the change:
After the change:
=> Swagger Bootstrap: Show required request DTO properties

src/ServiceStack.Interfaces/DataAnnotations/SqlServerMemoryOptimizedAttribute.cs, src/ServiceStack.Server/Caching/OrmLiteCacheClient.cs, tests/ServiceStack.Server.Tests/Caching/CacheClientTests.cs
Updated OrmLiteCacheClient for SQL Server in-memory optimized tables but interfacing out the CacheEntry, plus restricted the SqlServerMemoryOptimizedAttribute to decorate classes only.
=> Updated OrmLiteCacheClient for SQL Server in-mem optimized tables

src/ServiceStack/ServerEventsFeature.cs
If the subscription is expired or closed, then it shouldn't be receiving publications.
=> SSE - Skip broadcasting to expired subscriptions

src/ServiceStack.Client/ContentFormat.cs
Added Wire MimeType to IsBinary() check as I was getting an exception when trying to cache Wire formatted content without this.
I also noticed there currently isn't support for Wire format in `[Restrict(RequestAttributes.Wire)]`. I had a shot at doing this locally but it meant touching ServiceStack.Interfaces project (to update RequestAttributes and Feature classes) which resulted in a few issues relating to needing to update ServiceStack.Interfaces for other projects while I'm unable to sign it.
If Restrictions for Wire is something you think should be supported I can add the changes I've made to this P.R. (albeit they may be incomplete).
=> Updated ContentFormat.IsBinary() logic for Wire format

src/ServiceStack/ServiceStackHost.cs
SHA256 is not thread-safe  and concurrent use of ComputeHash can return an incorrect hash result.
This issue can be reproduced with a simple HelloWorld service and the following configuration:
```
public override void Configure(Container container)
{
var usersRepo = new InMemoryAuthRepository();
usersRepo.CreateUserAuth(new UserAuth() { UserName = "admin1" }, "pass1");
container.Register<IUserAuthRepository>(usersRepo);
this.Plugins.Add(new AuthFeature(
() => new AuthUserSession(),
new[] { new BasicAuthProvider() }));
// Uncomment the following to fix the concurrency issue
//container.Register<IHashProvider>(c =>
//{
//    return new SaltedHash();
//}).ReusedWithin(ReuseScope.None);
}
```
I used the Apache Bench tool to stress test the service.
When the concurrency flag is set to 1, all …
=> Register SaltedHash as a transient service.

NuGet/NuGetPack.cmd, build/build.proj, src/ServiceStack.Logging.Serilog/Properties/AssemblyInfo.cs, src/ServiceStack.Logging.Serilog/SerilogFactory.cs, src/ServiceStack.Logging.Serilog/SerilogLogger.cs, src/ServiceStack.Logging.Serilog/ServiceStack.Logging.Serilog.csproj, src/ServiceStack.Logging.Serilog/packages.config, src/ServiceStack.Logging.sln, src/ServiceStack.sln, src/packages/repositories.config, tests/ServiceStack.Logging.Tests/ServiceStack.Logging.Tests.csproj, tests/ServiceStack.Logging.Tests/UnitTests/SerilogFactoryTests.cs, tests/ServiceStack.Logging.Tests/UnitTests/SerilogLoggerTests.cs, tests/ServiceStack.Logging.Tests/UseCases/UsingSerilog.cs
- Created new ServiceStack.Logging.Serilog project.
- Added Implementation of ILog and ILogFactory for Serilog.
=> Added support for Serilog logging.

src/ServiceStack/FluentValidation/AbstractValidator.cs, src/ServiceStack/FluentValidation/AssemblyScanner.cs, src/ServiceStack/FluentValidation/DefaultValidatorExtensions.cs
**AbstractValidator**
re-added missing IRequiresRequest interface
reverting accidental change to exception message to use GetOperationName
adding missing Request set to ValidateAsync and Validate methods
**AssemblyScanner**
Correcting Netstandard preprocessor directives in AssemblyScanner
**DefaultValidatorExtensions** 
Restoring binary backwards compatability by removing Validate method's optional RuleSet string argument and creating separate method instead.
Few xml documentation updates for consistency in DefaultValidatorExtensions
=> Some corrections upon futher review and fix for binary compatibility breaking change

src/ServiceStack.HttpClient/JsonHttpClient.cs
This makes the JsonHttpClient mirror the behavior in [ServiceClientBase](https://github.com/ServiceStack/ServiceStack/blob/master/src/ServiceStack.Client/ServiceClientBase.cs#L1444) that passes the request object to the server.
=> Send request on JsonHttpClient.Patch(IReturnVoid)

src/ServiceStack/AppHostBase.NetCore.cs, src/ServiceStack/RequestContext.cs
Hey mythz, i posed some weird stackoverflow issue lately of getting weird redis errors.
I traced the bug to in our code but it i found the issue also lays in servicestack core. 
The requestContext can easily be turned into a static dictionary when touched directy & indirectly in startup. Or outside of a request. This would already create the AsyncLocal<Dictionary> and thus this dictionary would be given anywhere deeper in the pipeline: also every request gets this same Dictionary.
I solved it this way it now overrides this dictionary at the beginning over every request.
Another option, which wouldn't be water-thight but maybe a good addition: on `CreateItems` check if `ServiceStackHost.Instance.HasStarted` Otherwise throw an error, so people will see there bugs in code early on instead of …
=> Fix RequestContext going out of scope in .NetCore

src/ServiceStack/Caching/CacheClientPrefixer.cs, src/ServiceStack/ServiceStack.csproj
Adds ability to prefix the cache client using a decorator.
for example can be added on RedisManagerPool => ClientFactory for easy multi tenant use of the redis instance.
=> Adds CacheClientPrefixer that decorates ICacheClient commands with prefix

src/ServiceStack/Testing/MockHttpResponse.cs
When testing an using the `MockHttpRequest`, if you forget to initialise an AppHost in your tests (usually done once for all tests) you get the dreaded 'Object reference not set to an instance of an object.' NOT from `MockHttpRequest` but from `MockHttpResponse` with no clue as to the cause. 
This change ensures that you get a clue, that prompts you to initialise a ServiceStackHost in your tests first. It could even go further and point you to a page to demonstarte how to do that.
=> Update MockHttpResponse to give clue in testing

src/ServiceStack.Api.OpenApi/project.json
Currently it's including `openapi-ui`; however, the services looks for them at `swagger-ui` and this is not able to resolve the ui in .net core apps
=> Use proper directory for embedded resources

src/ServiceStack/NativeTypes/NativeTypesMetadata.cs, tests/ServiceStack.Common.Tests/NativeTypesTests.cs
Generated code for annotated DTOs was creating [ApiMember] with random property ordering. (I suspect the order of the `PropertyInfo` collection is not guaranteed by the CLR.
Each time we regenerated a client library from an endpoint using the built-in `/types/csharp` endpoint on an annotated DTO, the resulting diff was massive, even though the DTO shapes had not changed.
Given an annotated DTO of:
```C#
public class Item
{
[ApiMember(Description = "The ID of the item", IsRequired = true)]
public int Id { get; set; }
}
```
One run of the type generator would yield:
```C#
public class Item
{
[ApiMember(Description="The ID of the item", IsRequired=true)]
public int Id { get; set; }
}
```
After the next daily build, with no code changes, a subsequent run of the type generator would yield: …
=> Create generated code with predictable [ApiMember] property ordering.

src/ServiceStack/Auth/JwtAuthProviderReader.cs
ServiceRoutes is null by default and this was causing an exception to occur during application startup that was swallowed by the AppHost init procedure.
=> Check for null ServiceRoutes

src/ServiceStack/InProcessServiceGateway.cs
The original methods would always POST the request. I changed Publish and PublishAsync to mimic what was done in Send and SendAsync where it gets the verb using the IVerb interface of the request.
=> InProcessServiceGateway Publish and PublishAsync should now use the verb from the request dto.

src/ServiceStack/Host/AppDelegates.cs, src/ServiceStack/IAppHost.cs, src/ServiceStack/ServiceStackHost.cs, tests/ServiceStack.WebHost.Endpoints.Tests/TypedFilterTests.cs
I added a couple of overloads to ServiceStackHost for convenience purposes.
The overloads allow you to use the container to resolve an ITypedFilter<T> service(s).
It will then delay the resolve until the filter is actually called, allowing the container to correctly auto-wire the dependencies.
`RegisterTypedRequestFilter(c => c.Resolve<MyTypedFilter>());`
Otherwise, the service(s) would be resolved during the initialization, and results in a "Cannot resolve service or one of its auto-wired dependencies" exception. 
`RegisterTypedRequestFilter(container.Resolve<MyTypedFilter>());`
_Note: If there is already a recommended way to do this let me know. I was not aware of any so this is what we did to resolve our problem._
=> Added overloads for register typed filters

src/ServiceStack/IAppHost.cs, src/ServiceStack/ServiceStackHost.cs
Changed overloads for register typed filters to remove params keyword.
Original: #1155
=> Changed overloads for register typed filters

src/ServiceStack/Host/RequestBaseWrapper.cs
Removed unused local variables from RequestBaseWrapper. 
This should remove the unnecessary null checks against variables that are always null.
=> Removed unused locals in RequestBaseWrapper

src/ServiceStack.Common/CachedExpressionCompiler.cs
Added GetHashCode overrides to suppress compiler warnings from
CachedExpressionCompiler. Warnings exist because the Equals methods are
overridden, but the GetHashCode methods were not.
NOTE: There may be a better way to do this, but this seemed to be the most straightforward.
=> Added GetHashCode overrides to suppress warnings

src/ServiceStack/Host/HttpRequestAuthentication.cs, tests/ServiceStack.ServiceHost.Tests/HttpRequestAuthenticatonTests.cs
Fix for situation when authorization header is present but it is empty.
=> fix for getting bearer token when authorization header is empty

src/ServiceStack/NativeTypes/TypeScript/TypeScriptGenerator.cs
Given the following route:
generating native types for typescript produces the following output:
the `createResponse ` return value should be `false`, not `new boolean()`
=> Typescript type generator does not properly output a default value for the C# bool type.

src/ServiceStack.Client/ServiceClientBase.cs
I'd like this method to be protected so we can override `ServiceClientBase.HandleResponseException` and provide minimal changes to it, but still keep the default behavior of it as is. (see [discussion](https://forums.servicestack.net/t/serviceclientbase-new-authentication-behaviour/4659/3))
=> Make ThrowResponseTypeException protected

src/ServiceStack/Host/ServiceController.cs, tests/ServiceStack.WebHost.Endpoints.Tests/InProcessServiceGatewayRequestResponseFiltersTests.cs
this fixes a bug in ServiceController.ExecAsync - when instructed not to apply filters, Respone filters are applied anyway (but not Request filters, making it even worse in my case).
I've discovered it when using Service Gateway (Sync and Async), that's why the tests are using Gateway and not comparing Exec/ExecAsync directly. I suppose they could be made shorter but I believe they still show the point.
without the fix, the second test (using Gateway.SendAsync) fails as the list contains 3 elements (ResponseFilter is called for Internal Request made through Gateway)
=> GatewayExecuteAsync: don't apply response filters when applyFilters is false

src/ServiceStack.Logging.NLog/NLogLogger.cs, tests/ServiceStack.Logging.Tests/UnitTests/NLogTests.cs
Fixes bug introduced with #1171 
See also https://forums.servicestack.net/t/wierd-error-trying-to-instantiate-nlogger-with-servicestack/5115
=> Fixes NLog bug introduced when adding support for async PushProperty

.gitignore, NuGet/NuGetPack.cmd, NuGet/ServiceStack.Logging.Log4Net.Core/servicestack.logging.log4net.core.nuspec, build/build.proj, src/ServiceStack.Logging.Log4Net.Core/AssemblyInfo.cs, src/ServiceStack.Logging.Log4Net.Core/Log4NetFactory.cs, src/ServiceStack.Logging.Log4Net.Core/Log4NetLogger.cs, src/ServiceStack.Logging.Log4Net.Core/Log4NetProvider.cs, src/ServiceStack.Logging.Log4Net.Core/ServiceStack.Logging.Log4Net.Core.csproj, src/ServiceStack.Logging.sln
Support for ServiceStack.Core netstandard2.0 and include provider to works with ASP.net Core.
You can reuse the log classes to implement both systems:
LogManager.LogFactory = new Log4NetFactory("log4net.config");
loggerFactory.AddProvider(new Log4NetProvider());
or
loggerFactory.AddLog4Net();
=> Implements support for log4Net in Core

tests/NetCoreTests/ContainerTests.cs
This is an interesting case. On netcore, the `Request.QueryString.HasKeys()` in a service will return false even when keys are present and accessible from `Request.QueryString.AllKeys`.
This works fine if manually creating a `NetCoreQueryStringCollection` and using `HasKeys` but via the request pipeline, it doesn't.
This PR only adds the test to show it's a problem.
=> Add unit test to show issue with 'HasKeys' on netcore.

src/ServiceStack.Interfaces/DataAnnotations/ReturnAttribute.cs
Added the ReturnAttribute to implement in OrmLite.
Properties marked with this attribute will be included in the RETURNING (FireBird and PostgreSql) or OUTPUT (SqlServer) clause when building sql sentences for INSERT or UPDATE operations.
This allows to use SEQUENCES in SqlServer for Id columns instead of IDENTITY.
Also and not less useful, allows to get back field values that might be updated in database triggers when doing the same operations.
=> Added ReturnAttribute for use in OrmLite

src/ServiceStack.Client/AsyncServiceClient.cs, src/ServiceStack.Client/ServiceClientBase.cs, tests/ServiceStack.WebHost.Endpoints.Tests/AsyncServiceClientTests.cs, tests/ServiceStack.WebHost.Endpoints.Tests/ZipServiceClientTests.cs
**Problem:** When setting the RequestCompressionType on a JsonServiceClient and using the SendAsync-method a SerializationException occurs because the Content-Encoding header is not set in the WebRequest
**Proposed solution in this PR:**
I added the Property RequestCompressionType to the AsyncServiceClient and set it when setting the Property in the ServiceClientBase. The RequestCompressionType is then (anologous to the ServiceClientBase) added as a header before sending the WebRequest. I added tests to the AsyncServiceClientTests and the ZipServiceClientTests
=> RequestCompressionType is not considered when using AsyncServiceClient

src/ServiceStack.RabbitMq/RabbitMqBasicConsumer.cs, src/ServiceStack.RabbitMq/RabbitMqProducer.cs
This pull request allows consumers to set the prefetch count but still defaults to the most optimal as described in:
http://www.rabbitmq.com/blog/2012/04/25/rabbitmq-performance-measurements-part-2/
http://www.rabbitmq.com/amqp-0-9-1-reference.html
=> Make prefetch configurable

src/ServiceStack.RabbitMq/RabbitMqProducer.cs
PrefetchSize is not supported by RabbitMQ
[basic.qos](http://www.rabbitmq.com/specification.html#method-status-basic.qos)
>  Prefetch size limits are not implemented.
=> Allow PrefetchCount to be configured revert setting PrefetchSize as it is not supported by RabbitMQ

src/ServiceStack/Auth/ApiKeyAuthProvider.cs, src/ServiceStack/LocalizedStrings.cs
I found four magic strings when validating the ApiKey in the auth provider. In order to support localized messages it's important to replace these with the same static representations as with `ApiKeyRequiresSecureConnection` already in the code base.
=> Add support for localized error messages in ApiKeyAuthProvider

src/ServiceStack/ProxyFeature.cs
From my understanding this is a copy-paste issue and TransformRequest should be checked before execution.
=> Fix copy-paste bug in ProxyFeatureHandler

src/ServiceStack/IAppHost.cs, src/ServiceStack/Validation/ValidationFeature.cs, src/ServiceStack/Validation/ValidationFilters.cs, tests/ServiceStack.Common.Tests/FluentValidation/UserSeverityTests.cs
With FluentValidation you can set the Severity level to Info, Warning or Error using the WithSeverity extensions method.
The ValidationFeature does not distinguish between the different severity levels and will return an error response back to the caller regardless of the severity set.
This PR adds a flag to disable this behavior. 
Instead of getting an error response returned, if the response DTO inherits from IHasResponseStatus, the response status property will be populated with the failed validations and the meta dictionary property will contain the severity.
=> Add a flag to relax treating warnings/info as errors

src/ServiceStack/Host/ServiceController.cs, src/ServiceStack/ServiceStackHost.Runtime.cs
When a MultiRequest is being processed it would be useful for the rest of the pipeline to be able to obtain the index of the request within the batch. For example if an error occurs a `Meta` item could be added to the `ResponseStatus` which indicated the position that the error relates to.
This PR adds `MultiRequestIndex` as a req item that can be retrieved anywhere in the pipeline. If this is acceptable I'll add tests and refine the implementation.
=> Auto Batched Requests - share current req index with rest of pipeline

src/ServiceStack/ServiceStackHost.Runtime.cs, tests/ServiceStack.WebHost.Endpoints.Tests/AutoBatchTests.cs
Further to #1196 
* Add AutoBatchIndex for global response filters
* Add tests
=> Auto Batched Requests - share current req index with rest of pipeline part 2

src/ServiceStack/Host/ServiceRunner.cs, src/ServiceStack/Validation/ValidationFilters.cs
This allows the client to relate the error to the request which caused the error.
=> Add AutoBatchIndex to ResponseStatus.Meta for auto batched requests

src/ServiceStack/HttpRequestExtensions.cs, tests/ServiceStack.WebHost.Endpoints.Tests/AutoBatchTests.cs
Using this method to enumerate the requests batch ensures the same behaviour
as regular (non-custom) batch requests. Namely, the AutoBatchIndex item is
set correctly.
The new test shows usage with a custom batched request implementation. If the custom impl performs some kind of complex validation then performing this within the EachRequest "loop" will ensure the exceptions ResponseStatus.Meta is set as with non-customs.
=> Add ext method for use in Custom Batched Requests Implementations

src/ServiceStack/ServiceStackHost.cs
Even after ServiceStackHost has been disposed, the static event TaskScheduler.UnobservedTaskException holds a reference to the object and thus it is kept in memory throughout the lifetime of the application. This creates a problem with systems that have "soft" restarts where the app domain is never disposed, and ServiceStack is reinitialized multiple times.
=> Fix memory leak: After disposing ServiceStackHost is kept in memory

src/ServiceStack/Host/InMemoryRollingRequestLogger.cs, src/ServiceStack/HttpExtensions.cs, src/ServiceStack/HttpResultUtils.cs, tests/ServiceStack.WebHost.Endpoints.Tests/RequestLogsFeatureTests.cs
Responses of type ErrorResponse are not logged to the error log.
1. **HttpExtensions.EndHttpHandlerRequest** and **EndHttpHandlerRequestAsync** do not include the response in the call to **IRequestLogger.Log**, thus downstream handlers see the response as null (this also appears to prevent non-error responses from being logged when EnableResponseTracking is true),
2. **HttpResultUtils.IsErrorResponse** only considers **IHttpError** or **Exception** to be an error response, and thus
3. **InMemoryRollingRequestLogger.ToSerializableErrorResponse** does not serialize an ErrorResponse as an error.
Added tests fail in pre-PR code.
First PR, so comments/changes/criticisms welcome.
=> Request Logging: Ensure that an ErrorResponse is logged as an error.

src/ServiceStack/js/ss-utils.js
There can be multiple forms on a single webpage. Form data is submitted via key value pairs where the key is based upon the input `name` attribute and not the `id` attribute since html entity id's need to be unique. The proposed change defaults to apply errors via the input `name` attribute rather than the `id` as that will correlate back to the ServiceStack Service's request DTO, which will then correctly find the correct fieldId to apply the errors. This would then also avoid the issue with check and radio inputs where there can be multiple of them.
Example: 
If there are two forms on a webpage and they both have an email input, only one can have an `id` of 'email'. The current way `applyErrors()` works defaults to the `id` attribute and not the `name` attribute, so only one form can …
=> Change applyErrors to default to `name` attribute

src/ServiceStack.Logging.NLog/NLogLogger.cs
Give Exception-object to NLog when called like this:
`Log.Fatal(ex);`
=> NLogLogger - Allow NLog to capture Exception-object when only parameter

src/ServiceStack.Logging.NLog/ServiceStack.Logging.NLog.csproj, tests/ServiceStack.Logging.Tests/UnitTests/NLogTests.cs
Unit test for #1210 (Requires NLog 4.5.4 that includes https://github.com/NLog/NLog/pull/2586)
=> NLogLogger - Allow NLog to capture Exception-object when only parameter (unit test)

src/ServiceStack.HttpClient/JsonHttpClient.cs
JsonHttpClient sends a refresh request if `RefreshToken` is set, but
while processing the refresh, the underlying `HttpClient` is not updated,
so subsequent requests with the same JsonHttpClient will again
need to refresh the out-of-date `BearerToken`.  The update to
`BearerToken` is never reflected in `HttpClient`.  Note that this only
happens with token-only authorization.  Cookie and Basic auth properly
update the `HttpClient`.
There are also some whitespace deletions in this PR, but those can be reverted.
Let me know if you have any questions.
=> Refresh BearerToken properly in JsonHttpClient

src/ServiceStack/Internal/IServiceStackAsyncDisposable.cs, src/ServiceStack/ServerEventsFeature.cs
event-subscriptions `Dispose` path appears to be manifesting spiral-off-death (https://blog.marcgravell.com/2019/02/fun-with-spiral-of-death.html)
- introduce an internal `DisposeAsync` API (not public due to net45 TFM)
- use this API whenever disposing on async path
- implementation is virtually the same as sync `Dispose`, but using `Task.Delay` instead of `Thread.Sleep`
Additional observations for future consideration:
- `IAsyncDisposable.DisposeAsync` is an official API now down to net461 (via https://www.nuget.org/packages/Microsoft.Bcl.AsyncInterfaces/)
- may want to consider when/if `ConfigureAwait(false)` is appropriate on the async code generally
- I've used [`MutexSlim`](https://github.com/mgravell/Pipelines.Sockets.Unofficial/tree/master/src/Pipelines.Sockets.Unofficial/Threading …
=> Address spiral-of-death in event-subscription Dispose path

src/ServiceStack.Extensions/ServiceStack.Extensions.csproj, src/ServiceStack.GrpcClient/GrpcConfig.cs, src/ServiceStack.GrpcClient/GrpcServiceClient.cs, src/ServiceStack.GrpcClient/ServiceStack.GrpcClient.csproj, src/ServiceStack.Interfaces/IQuery.cs, src/ServiceStack.ProtoBuf/ProtoBufFormat.cs, src/ServiceStack.ProtoBuf/ServiceStack.ProtoBuf.Core.csproj, src/ServiceStack.ProtoBuf/ServiceStack.ProtoBuf.csproj, tests/ServiceStack.Extensions.Tests/GrpcTests.cs, tests/ServiceStack.Extensions.Tests/ProtobufTests.cs, tests/ServiceStack.WebHost.IntegrationTests/ServiceStack.WebHost.IntegrationTests.csproj, tests/ServiceStack.WebHost.IntegrationTests/packages.config
Context: `Query*` DTOs are currently implemented by subclassing (for example) `QueryDb<T>`, which subclasses `QueryBase`. All of the shared query info is on `QueryBase`, however this results in a very awkward to work with protobuf `message` schema. Not a huge problem for .NET-.NET, but awkward for x-plat.
This proposed change changes this by special-casing anything that subclasses `QueryDb`; when detected, it applies a fixed offset (currently 32) to all the regular fields in the type, and instead of absorbing the base type via protobuf-net's spoofed inheritance, it hoists all of the relevant fields directly into the 32-field reserved chunk (only 7 currently in use, so space for a few extra). This gives a far more pleasing shape, and avoids a lot of unnecessary overhead related to how …
=> Flatten query DTOs into the request DTO (caution: changes DTO shape; requires major)

src/ServiceStack.GrpcClient/GrpcServiceClient.cs, tests/ServiceStack.Extensions.Tests/GrpcTests.cs
- instead of hard-coding `QueryBase`, detect all request DTOs as things that inherit `IReturn[Void|<T>]`
- when identified, look at the type hierarchy for each base class in the tree
- each level offsets the more-derived-types fields by 100
- copy the fields from each discovered level into the type under consideration
=> generalize request DTO flattening

src/ServiceStack/Funq/Container.Adapter.cs
As an extension to the previous commit, just adding these overloads for GetServiceEntryNamed<T> and ExistsNamed<T> that are needed for named registrations.
=> Add IOC GetServiceEntryNamed<T> and ExistsNamed<T>

src/ServiceStack.Extensions/GrpcFeature.cs, src/ServiceStack.Extensions/ServiceStack.Extensions.csproj, src/ServiceStack.GrpcClient/GrpcConfig.cs, src/ServiceStack.GrpcClient/GrpcServiceClient.cs, src/ServiceStack.GrpcClient/ServiceStack.GrpcClient.csproj, src/ServiceStack.ProtoBuf/ServiceStack.ProtoBuf.Core.csproj, tests/CheckGrpc/CheckGrpc.csproj, tests/CheckWebCore/CheckWebCore.csproj
1. fix AddField typo
2. use AfterApplyDefaultBehaviour to move timing of type configuration (moves config code to GrpcConfig)
3. above needs newer protobuf-net build
Main change is 1; this seems to have been a change when `AddField` was refactored after my earlier PR; [original code](https://github.com/ServiceStack/ServiceStack/commit/14dd3eb9d29661c7990c7f30c8508d9bfc1a988d#diff-eeb5a8117e8744e028e08c16d2c43d97R746) added `field.ItemType`; code in "master" added `field.ItemType ?? field.MemberType`, which incorrectly tries to configure everything as "repeated". If this was done for a specific reason, let me know - I can look into that.
2. moves type config to use the newer protobuf-net API that allows configuration *during discovery*, avoiding a lot of timing problems; this required …
=> Fix broken grpc tests

src/ServiceStack/NativeTypes/Dart/DartGenerator.cs
I was getting a warning on this code generated.
Source: https://dart-lang.github.io/linter/lints/avoid_return_types_on_setters.html
=> Dart - avoid_return_types_on_setters style

src/ServiceStack.Common/Script/JsToken.cs, src/ServiceStack.Common/Script/ScriptConfig.cs, src/ServiceStack.Common/Script/ScriptContext.cs, tests/ServiceStack.WebHost.Endpoints.Tests/ScriptTests/JsLiteralTests.cs
I'm considering using #Script/Js.eval as an embedded language in a financial application, for user defined formulas. However currently all "decimal" numbers are parsed as `double`s. I appreciate this is in keeping with the JavaScript roots.
It would be great if there was an opt-in option to parse numbers as `decimal`s instead of `double`s.
I've added a static flag to the `ScriptContext`, but this could be an instance field, it would just need passing all the way done 🐢.
Please let me know if this is something you'd consider allowing, if it is I can look at adding tests and changing to an instance field etc.
=> #Script - Option to parse numbers as decimals

src/ServiceStack.HttpClient/JsonHttpClient.cs, tests/ServiceStack.WebHost.Endpoints.Tests/ServiceClientTests.cs
`JsonHttpClient` was disposing the injected `HttpMessageHandler` preventing re-use.
A `SocketsHttpHandler` instance pools connections so can be long-lived [without fear of socket exhaustion or DNS problems](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-3.1#alternatives-to-ihttpclientfactory).
For situations where the same `JsonHttpClient` can't be re-used (different authentication for example), it would be useful to at least re-use the handler and underlying connections (with cookies off).
=> Don't dispose HTTP message handler if it was injected

src/ServiceStack/Host/Handlers/ServiceStackHandlerBase.cs
String interpolation for `SerializationException` calls `ex.ToString()` under the hood which inadvertently includes the stack trace in the error message.
=> Remove stack trace from SerializationException message

src/ServiceStack/AppHostBase.NetCore.cs, src/ServiceStack/LogExtensions.cs
on NetCore with the UseServiceStack it delegates in Microsoft.Extensions.Logging ILogger if  LogManager.LogFactory == null, but LogManager.LogFactory could not be null because it coerce witha a new NullLogFactory(false)
https://github.com/ServiceStack/ServiceStack/blob/master/src/ServiceStack.Interfaces/Logging/LogManager.cs#L17-L21
```csharp
public static ILogFactory LogFactory
{
get => logFactory ?? new NullLogFactory();
set => logFactory = value;
}
```
=> Fix default LogFactory in NetCore

src/ServiceStack/Auth/NetCoreIdentityAuthProvider.cs
There are some use cases where it would be helpful to run additional logic in the PreAuthenticate method of the NetCoreIdentityAuthProvider
=> Make NetCoreIdentityAuthProvider virtual

src/ServiceStack/AppHostExtensions.cs
The .NET Core version of the AppHostBase throws an exception when PathBase doesn't start with '/'. ResolveStaticBaseUrl adds an additional '/' which in turn breaks the login.html page. The quickest way to fix this is to remove the concatenation of the '/' to appHost.PathBase in ResolceStaticBaseUrl. However, I wasn't sure if in the Framework version of this code allows setting PathBase to a value that doesn't start with '/' so I've replaced the double '//' here using ReplaceAll. If the Framework version works the same as the .NET Core version then this could just be simplified as mentioned above.
=> Remove extra slash that is added to PathBase when calling ResolveStaticBaseUrl

src/ServiceStack/CacheResponseAttribute.cs
Use async cache client if registered to avoid possible NRE when using `ICacheClientAsync`.
=> Use async cache client if registered to avoid possible NRE

src/ServiceStack/Auth/DiscordAuthProvider.cs
Basic Discord OAuth2 support. Discord doesn't have much info on users so username is used as `name` or `DisplayName`. 
Enforces email verification due to it not being required for user accounts on discord.
Discards `username` as Discord's is easy to change and comes with randomly generated discriminator that wouldn't mix well with how SS forces username unique requirement on features like registration, discriminator also regenerated on username change. Only `id` or `user_id` required for Discord API lookups.
=> Add DiscordAuthProvider

src/ServiceStack.Server/AutoQueryFeature.cs, tests/ServiceStack.WebHost.Endpoints.Tests/AutoQueryTests.cs
Note that I wasn't able to run all tests (no SQL Server on hand and only .NET core), but those that do run succeed.
=> #767 Add support for custom select in AutoQuery filters.

src/ServiceStack.Common/GitHubGateway.cs, tests/ServiceStack.WebHost.Endpoints.Tests/GithubGatewayTests.cs
Support added to IGitHubGateway to make it easier to fetch specific zip urls of a specific tag in a repository. This would make it easier for tools like `dotnet-app` to add support for using previous template versions for those not ready to use latest versions.
=> Add support for fetching ZipUrls for a specific GitHub tag

.github/workflows/build-azure.yml, .github/workflows/build-blazor.yml, .github/workflows/build-core.yml, .github/workflows/build-logging.yml, .github/workflows/myget-pack.yml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: neilnaveen <42328488+neilnaveen@users.noreply.github.com>
=> chore: Set permissions for GitHub actions

ServiceStack/src/ServiceStack/modules/shared/js/core.js, ServiceStack/tests/NorthwindAuto/ServiceModel/Talent.cs, ServiceStack/tests/NorthwindAuto/shared/js/core.js, ServiceStack/tests/ServiceStack.WebHost.Endpoints.Tests/ServerEventTests.cs
Fix locode check for when auth is required but not specific role or permission is. Related to [issue raised in the customer forums](https://forums.servicestack.net/t/authentication-locode-and-roles/10839).
=> Fix locode check for when auth is required but not specific role

ServiceStack.Aws/src/ServiceStack.Aws/FileStorage/S3FileStorageProvider.cs
We found that when using the AWS S3 service, we are not able to create the subfolder. Whenever we give the subfolder string to the `CreateFolder` method, the subfolder cannot be created successfully (we check the S3 portal). 
We write this PR to support the subfolder creation in AWS S3. Thanks!
=> Support the subfolder creation of S3

ServiceStack.Aws/tests/ServiceStack.Aws.Tests/FileStorage/FileStorageProviderCommonTests.cs, ServiceStack.Aws/tests/ServiceStack.Aws.Tests/FileStorage/S3FileStorageProviderTests.cs
As the AWS bucket re-creation may not happen immediately, I add a thread sleep for 5 seconds after the bucket is deleted and before its creation. AWS doc:
https://aws.amazon.com/premiumsupport/knowledge-center/s3-conflicting-conditional-operation/
What's more, the `us-east-1`region will behave differently with others due to some legacy issues, so I think it is better to use other regions (us-east-2) instead of the us-east-1, as documented:
https://github.com/aws/aws-sdk-net/issues/2083
=> prevent bucket re-creation error

ServiceStack.OrmLite/src/ServiceStack.OrmLite/OrmLiteSchemaModifyApi.cs, ServiceStack.OrmLite/tests/ServiceStack.OrmLite.Tests/Migrations/Migration1004.cs
Issue related to logic for `isPrimaryKey` and `isFirst` property when building the `FieldDefinition`. Since migrations use inner classes related to only the difference.,
Updated  `AddColumn<T>` to check if field is `Id`, otherwise set `IsPrimaryKey` to false after creation field defintion.
=> Add failing test for use of `AddColumn<T>` for migrations.

ServiceStack.Redis/src/ServiceStack.Redis/RedisExtensions.cs, ServiceStack.Redis/tests/ServiceStack.Redis.Tests/RedisExtensionTests.cs
Azure Redis Cache automatically generates passwords based on Base64 conversion, which add an "=" to the end of the password string.  This is not properly handled by `RedisExtensions.ToRedisEndpoint()`.
=> Fix redis connection string parsing bug

ServiceStack/src/ServiceStack/ServerEventsFeature.cs
Fix: ServerEvents.GetSubscriptionInfo(id) throws a NullReferenceException for non existing sessions
=> Fix ServerEvents.GetSubscriptionInfo(id) NullReferenceException if subscription is not valid

ServiceStack/src/ServiceStack/Validators.cs, ServiceStack/tests/ServiceStack.WebHost.Endpoints.Tests/DeclarativeValidationTests.cs
Fix for [issue reported on customer forums](https://forums.servicestack.net/t/validation-trouble-for-nested/11180) when parent IEnumerable<T> property has own declarative validation attributes, child attributes are skipped. This removes the check so that nested validation is also applied in this case by removing the existing rule check for a parent property validation.
=> Fix nested child declarative validation when parent properties also have validation

ServiceStack.Aws/src/ServiceStack.Aws/Sqs/ISqsQueueManager.cs, ServiceStack.Aws/src/ServiceStack.Aws/Sqs/SqsMqServer.cs, ServiceStack.Aws/src/ServiceStack.Aws/Sqs/SqsMqWorkerInfo.cs, ServiceStack.Aws/src/ServiceStack.Aws/Sqs/SqsQueueManager.cs, ServiceStack.Aws/src/ServiceStack.Aws/Sqs/SqsQueueName.cs
Enhanced the SQS Message Queuing to support the AWS SDK parameter for specifying the AWS Account Id of the SQS Message queue, which is used for cross-account SQS message queue access.
- Parameter can be optionally be specified at Message Queue configuration, which if configured, will pass it into the Get Queue Name API call request object (the GetQueueUrlRequest) which returns the AWS SQS Queue name. Past this point the queue logic and methods remain unchanged as the API response always included an account Id regardless of us specifying one to get a queue in a different AWS Account.
=> Add support for QueueOwnerAWSAccountId parameter of GetQueueUrlRequest

ServiceStack/src/ServiceStack/NativeTypes/TypeScript/TypeScriptGenerator.cs, ServiceStack/tests/ServiceStack.Common.Tests/NativeTypesTypescriptGeneratorTests.cs
We found out the TypeScriptGenerator doesn't play well with 2d+ arrays: 
```c#
var gen = new TypeScriptGenerator(null);
var result = gen.Type("String[][]", null);
```
result is `string[]` instead of `string[][]`
=> fix invalid 2d array type declaration in TypeScriptGenerator

ServiceStack.OrmLite/src/ServiceStack.OrmLite/Expressions/SqlExpression.cs, ServiceStack.OrmLite/tests/ServiceStack.OrmLite.Tests/OrmLiteSelectTests.cs
In some cases we don't want to execute the EscapeWildcards operation, but in order to be consistent with the previous behavior, we implement it as an opt-out.
=> Make EscapeWildcards as opt-out

ServiceStack/src/ServiceStack.Server/AutoQueryFeature.AutoCrud.cs
Encountered problem when trying to do a bulk soft delete in a loop.  There was an exception thrown in the middle of the update but when I rolled back the transaction, the updates for the soft deletes up to that point were committed.
The delete method delegates to the UpdateInternal method but did not pass its db parameter along causing the existing connection to reset and transaction is unable to rollback the updates.
=> Pass connection parameter to called UpdateInternalAsync

ServiceStack.OrmLite/src/ServiceStack.OrmLite/Expressions/SqlExpression.Join.cs, ServiceStack.OrmLite/src/ServiceStack.OrmLite/Expressions/SqlExpression.cs, ServiceStack.OrmLite/tests/ServiceStack.OrmLite.Tests/OrmLiteSelectTests.cs, ServiceStack.OrmLite/tests/ServiceStack.OrmLite.Tests/OrmLiteSelectTestsJoinAliasTests.cs
Consider the following code snippet(from OrmLiteSelectTestsJoinAliasTests.cs)
```csharp
var sqlExpression = db
.From<Channel>(x =>
{
x.UseSelectPropertiesAsAliases = true;
x.UseJoinTypeAsAliases = false;//Feature flag
})
.LeftJoin<Channel, Region>((x, y) => x.Area == y.Id)
.LeftJoin<Channel, VqdStateResult>(
(x, z) => x.Id == z.Code && (z.Type == TestType.Vqd) && (z.DstType == NttType.Channel),
new TableOptions()
{
Alias = "z"
})
.LeftJoin<Channel, OcrResult>(
(x, m) => x.Id == m.Code && m.Type == TestType.Osd && m.DstType == NttType.Channel, new TableOptions()
{
Alias = "m"
})
.LeftJoin<Channel, LinkResult>(
(x, h) => x.Id == h.Code && h.Type == TestType.Link && h.DstType == NttType.Channel, new TableOptions()
{
Alias = "h"
})
.Where(x => x.DstType == NttType.Channel && x.Delete == 0) …
```
=> JoinAlias enhancements

ServiceStack.OrmLite/src/ServiceStack.OrmLite/Migrator.cs, ServiceStack.OrmLite/tests/ServiceStack.OrmLite.Tests/Migrations/MigrationTests.cs
Check each previously run migration to avoid the issue where multiple developers are working on the same shared development environment. Issue relates to the assumption that migration classes would not be deleted. If accidentally done, all previous migrations will attempt to be rerun. This was caused by only ever checking the last run migration via the `.Limit(1)` at the end of the query.
This change selects all rows in `Migration` to check against each known `migrationType` to validate if it needs to be rerun or not. Optionally, we could optimize to the last `N` migrations like `5` as this would be very unlikely to hit the same issue but I guess still possible.
Related to raised issue in [customer forums](https://forums.servicestack.net/t/migration-where-local-migration-class-es-not-prese …
=> Check each previously run migration before attempting to rerun

ServiceStack.Redis/src/ServiceStack.Redis/RedisSentinelWorker.cs, ServiceStack.Redis/tests/ServiceStack.Redis.Tests.Sentinel/RedisSentinelFailOverTests.cs
Unhandled exception when getting a ready-only client from PooledRedisClientManager when the first of multiple sentinel hosts is down.
=> Fixing unhandled exception in sentinel worker

ServiceStack/src/ServiceStack/Funq/Container.cs, ServiceStack/tests/ServiceStack.ServiceHost.Tests/IoCTests.cs
MS DI doesn't have the named services feature (yet) therefore it's quite common pattern to overcome it with factory func:
```
.AddSingleton<Func<string, Func<IService>>>(services => name => name switch {
"foo" => () => services.Resolve<FooService>(),
"bar" => () => services.Resolve<BarService>()
})
```
however the injection of such factory function into ServiceStack services failed mysteriously.
This is because Funq decided to wrap it in Lazy Resolver before checking the presence of the exact registration in an Adapter.
=> Funq: Try resolving service from Adapter first, before applying Lazy Resolver

ServiceStack.OrmLite/src/ServiceStack.OrmLite.Firebird/FirebirdOrmLiteDialectProvider.cs
Allows for scaffolding crud endpoints using Autoquery.
N.B: It trims whitespace from the table names since RDB$RELATION_NAME is CHAR(31) which pads the string with spaces. This will cause scaffolding to fail on tables like '__EFMigrationsHistory'.
This was just a quick fix I had to implement while trying to test ServiceStack today. Might be a better way to accomplish this with a better understanding of the framework.
=> Update FirebirdOrmLiteDialectProvider to include ToTableNamesStatement

ServiceStack/src/ServiceStack.RabbitMq/RabbitMqBasicConsumer.cs, ServiceStack/src/ServiceStack.RabbitMq/RabbitMqExtensions.cs, ServiceStack/src/ServiceStack.RabbitMq/RabbitMqMessageFactory.cs, ServiceStack/src/ServiceStack.RabbitMq/ServiceStack.RabbitMq.csproj, ServiceStack/src/ServiceStack.RabbitMq/SharedQueue.cs, ServiceStack/tests/ServiceStack.Common.Tests/Messaging/RabbitMqTests.cs
The RabbitMQ.Client dependency was updated from version 5.2.0 to version 6.8.1. As a result, several changes have been made to the existing codebase. Changes include replacing the QueueingBasicConsumer with RabbitMqBasicConsumer, altering usage of RequestedHeartbeat, and refactoring ways to handle message body. Additionally, a new SharedQueue class has been introduced.
=> Update RabbitMQ.Client to version 6.8.1 and refactor code accordingly.

CONTRIBUTORS.md, ServiceStack.Text/src/ServiceStack.Text/PathUtils.cs, ServiceStack.Text/tests/ServiceStack.Text.Tests/CombinePathTests.cs
Updated path combining to safeguard from whitespaces in addition to the existing null and empty checks. This is so it doesn't combine unnecessary whitespaces and forward slashes to the path.
=> Update path utils to safeguard whitespaces.

ServiceStack.OrmLite/src/ServiceStack.OrmLite.Oracle/ServiceStack.OrmLite.Oracle.Core.csproj, ServiceStack.OrmLite/src/ServiceStack.OrmLite/OrmLiteConfig.cs, ServiceStack.OrmLite/src/ServiceStack.OrmLite/OrmLiteConnection.cs, ServiceStack.OrmLite/src/ServiceStack.OrmLite/OrmLiteExecFilter.cs, ServiceStack.OrmLite/src/ServiceStack.OrmLite/OrmLiteWriteApi.cs
1. Other libraries such as ``Mysql``, ``MysqlConnector``, etc. all have ``*.Core`` versions.
2. There is currently a ``GetLastSql`` extension function, but this is not intuitive for sql with parameters, and it can even be said to be meaningless, because even if the sql is obtained from the log, no verification and debugging can be performed at the database level.
Therefore, relevant infrastructure has been added so that complete sql statements can be obtained
=> Add missing ServiceStack.OrmLite.Oracle.Core.csproj

ServiceStack.Text/src/ServiceStack.Text/Common/DeserializeType.cs, ServiceStack/tests/ServiceStack.Common.Tests/DeserializeTypeTests.cs
During my update from ServiceStack 5.9.2 to 8.2.2 I figured out that the behavior changed.
The test ArrayThatContainsUnknownType_ShouldContainNullItem that's failing without the fix explains my issue. (       Assert.That(stub.Stubs, Is.Not.Null);)
To be coherent with DeserializeTypeRefJson., You can check the nullability of the type before calling AssertAllowedRuntimeType which fails with an exception
=> Allow to deserialize unknown sub type

ServiceStack.OrmLite/src/ServiceStack.OrmLite/Expressions/SqlExpression.cs, ServiceStack.OrmLite/tests/ServiceStack.OrmLite.Tests/ExpressionVisitorTests.cs
I accidentally found that ormlite generated incorrect sql for ``Func<T>`` related calls. This modification solved the problem, but I am not sure if there are any omissions or hidden dangers. Please check it out. 
Thank you
=> Support evaluate InvocationExpression like MethodCallExpression

ServiceStack.OrmLite/tests/ServiceStack.OrmLite.Tests/Expression/ConditionalExpressionTest.cs, ServiceStack.OrmLite/tests/ServiceStack.OrmLite.Tests/Expression/TestType.cs
MS Sql doesn't support the statements like this:
```sql
SELECT * FROM _mytable
WHERE not COALESCE(_is_bool, 0)
```
It has to be:
```sql
SELECT * FROM _mytable
WHERE COALESCE(_is_bool, 0) = 0
```
There is unit test in this PR: 
`Can_use_coalesce_with_nullable_bool`
=> Coalesce with nullable bool

ServiceStack/src/ServiceStack/Host/GatewayRequest.cs, ServiceStack/tests/ServiceStack.WebHost.Endpoints.Tests/ServiceGatewayTests.cs
Currently when making a call through the Gateway the Files from the Request object is not set on the GatewayRequest
=> Set GatewayRequest.Files from IRequest in FromRequest

ServiceStack/src/ServiceStack.Client/JsonApiClient.cs
When during `JsonApiClient.SendAsync` an exception was thrown, it was catched and instead an `WebServiceException` thrown. The original exception was ignored, same for the `HttpResponseMessage` which was passed to the internal `CreateException` method.
We had cases where the request itself was successful with a HTTP 200, but an `WebServiceException` was thrown. What we saw in (OpenTelemetry) logs:
exception.message:
```
Exception of type 'ServiceStack.WebServiceException' was thrown.
```
exception.stacktrace:
```
500 Code: Exception of type 'ServiceStack.WebServiceException' was thrown., Message: Exception of type 'ServiceStack.WebServiceException' was thrown.
```
This PR passes the actual exception as inner exception to the created `WebServiceException` and also sets the message to the …
=> Pass inner exception to exceptions thrown in JsonApiClient

ServiceStack/src/ServiceStack.Jobs/BackgroundsJobFeature.cs, ServiceStack/src/ServiceStack.Jobs/SqliteRequestLogger.cs
Fixes an issue where if the DbDir is a root path that the monthly database doesn't get incorrectly prefixed with the content root path of the app
=> If path is rooted ignore Content Root Path

ServiceStack/src/ServiceStack.Jobs/AdminJobServices.cs
Missed that AdminJobInfo requests need to also look at the correct directory
=> Ensure AdminJobInfo request get the correct DbDir

ServiceStack.Text/src/ServiceStack.Text/StringBuilderCache.cs
Motivation: 
The default capacity may cause multiple expansions within StringBuilder. For scenarios where strings are expected to be larger, a larger capacity can be directly allocated to improve performance
=> Add capacity parameter to StringBuilderCacheAlt.Allocate for custom sizing
