- src/ServiceStack.Authentication.OAuth2/InstagramOAuth2Provider.cs
- src/ServiceStack.Authentication.OAuth2/ServiceStack.Authentication.OAuth2.csproj
We need to include System.Runtime.Serialization to the project in order to increase the default max depth quota.
> Add Instagram OAuth2 Provider.

- src/ServiceStack.Common/EnumExtensions.cs
GetDescription checks several description attributes in addition to
System.ComponentModel.DescriptionAttribute including
ServiceStack.ApiAttribute and
ServiceStack.DataAnnotations.DescriptionAttribute
> Use AttributeExtensions.GetDescription in EnumExtensions.ToDescription

- src/ServiceStack.Authentication.OAuth2/FourSquareOAuth2Provider.cs
- src/ServiceStack.Authentication.OAuth2/MicrosoftLiveOAuth2Provider.cs
- src/ServiceStack.Authentication.OAuth2/ServiceStack.Authentication.OAuth2.csproj
Added a FourSquare OAuth2 Provider and made a small change to the Microsoft Live OAuth2 provider to simplify code. I haven't fully tested this provider and I'm not sure if I handled the population of the auth tokens correctly. There may be a better way to do this - I would love feedback.
> Added a FourSquare OAuth2 Provider

- src/ServiceStack.Razor/Managers/RazorPageResolver.cs
> ServiceStack.Razor: fix warning CS0168

- src/ServiceStack/Host/HttpListener/HttpListenerBase.cs
Add quotes around urlacl user so user names can have spaces
> Add quotes around urlacl user

- src/ServiceStack.Server/AutoQueryFeature.cs
missed during refactoring c4f8af70e6aa51313d89807940d7d13abaa87710
> generate suffix if no alias supplied  

- src/ServiceStack.RabbitMq/RabbitMqMessageFactory.cs
- src/ServiceStack.RabbitMq/RabbitMqProducer.cs
- src/ServiceStack.RabbitMq/RabbitMqQueueClient.cs
- src/ServiceStack.RabbitMq/RabbitMqServer.cs
- src/ServiceStack.RabbitMq/RabbitMqWorker.cs
It would be good to have the possibility to extend RabbitMq classes (e.g. for adding support for ProtoBuf) so I made the metods virtual.
> Make RabbitMq public API's virtual

- src/ServiceStack/HttpExtensions.cs
- src/ServiceStack/ServiceHost/ServiceController.cs
> Backporting patch for issue #335 to v3

- lib/js/JsonServiceClient.closure.js
- lib/js/JsonServiceClient.js
I needed to add the Patch verb for a project I am working on. I couldn't find any tests for the JsonServiceClient.js to update with this change. Also not sure if this is the right place to contribute this change as the JsonServiceClient.js and JsonServiceClient.closure.js was in the lib folder?
> Added Patch method to JsonServiceClient.js and JsonServiceClient.closure.js

- src/ServiceStack/Metadata/BaseMetadataHandler.cs
- src/ServiceStack/Metadata/BaseSoapMetadataHandler.cs
- tests/Check.ServiceModel/Rockstar.cs
Added support Cyrillic symbols in description attributes in metadataPage
s
> Added support Cyrillic symbols in description attributes

- src/ServiceStack.Client/ServerEventsClient.cs
Add ability to change baseUri for `ServerEventsClient`. Restart connection is required after change baseUri. Which can be performed manually.
> Allow ServerEventsClient to change baseUri.

- src/ServiceStack.Interfaces/Messaging/QueueNames.cs
> QueueNames<T> does not respect QueuePrefix (Clean Commit and whitespace)

- src/ServiceStack/Host/Handlers/ServiceStackHandlerBase.cs
Fixes https://github.com/ServiceStack/Issues/issues/447
> Add inner exception in serialize request

- src/ServiceStack.Common/ExpressionUtils.cs
- tests/ServiceStack.Common.Tests/ExpressionUtilsTests.cs
Fixes https://github.com/ServiceStack/Issues/issues/449
> Fix exception when trying to get member from base type

- license.txt
> Updated spelling

- src/ServiceStack/ServerEventsFeature.cs
Currently if a client disconnects while a channel is being notified, it causes an error to be thrown when attempting to SetResult on the TaskCompletionSource. This patch will prevent setting the result on the
task if it's already completed. It will also prevent attempting to notify a subscription where the underlying connection is already closed (currently the notify calls publish which throws an exception which then
unsubscribes the current subscription - this will prevent the exception, and simply unsubscribe.)
> Handle disconnected ServerSentEvent subscriptions

- src/ServiceStack/NativeTypes/TypeScript/TypeScriptGenerator.cs
This change is the address issue raised in a GitHub comment regarding multiple inheritance.
https://github.com/ServiceStack/ServiceStack/commit/5b0b9e6b80870d22664c703acec69d4d45c09827#commitcomment-18282539
This should ensure proper ordering of base types for generation.
> Typescript inheritance fix

- src/ServiceStack.Logging.Elmah/ElmahLogFactory.cs
Support for Elmah logging outside of HttpApplication - Self Hosted.
> ElmahLogFactory.cs: HttpApplication is optional in case of self hosting

- src/ServiceStack.Logging.Elmah/ElmahLogFactory.cs
- src/ServiceStack/Html/Minifiers.js.cs
Updated to latest version from https://github.com/douglascrockford/JSMin/blob/master/jsmin.c
Incorporated changes into .cs file and added optional ignoreErrors flag so a startup will not crash but simply return the non minified version of a javascript file.
> JavaScript minifier

- src/ServiceStack/ServiceStackHost.cs
> Add documentation to the ServicestackHost.

- src/ServiceStack.Client/Serialization/KeyValueDataContractDeserializer.cs
- src/ServiceStack.Client/Serialization/StringMapTypeDeserializer.cs
- src/ServiceStack/Host/NetCore/NetCoreRequest.cs
- src/ServiceStack/NetCore/NetCoreQueryStringCollection.cs
- src/ServiceStack/ServiceStack.Signed.csproj
- src/ServiceStack/ServiceStack.csproj
- tests/ServiceStack.WebHost.Endpoints.Tests/CacheServerFeatureTests.cs
.NET Core benchmark  `/json/reply/hello?name=world` increased performance from 38K rps to 46K rps on desktop Core I5 (4 cores) and from 26K rps up to 29K rps on Azure Standard_F4s machine
> Performance improvements

- src/ServiceStack/Platforms/PlatformNet.HostConfig.cs
See https://forums.servicestack.net/t/upgrade-to-4-5-6-get-error/3475/2
> Fix NRE when <handlers> are defined in <location> tag

- src/ServiceStack.Interfaces/RequestLogEntry.cs
- src/ServiceStack/Host/InMemoryRollingRequestLogger.cs
- Fixed a possible Null Reference Exception in InMemoryRequestLogger
- Added additional properties to RequestLogEntry
> Minor Logging Enhancements

- src/ServiceStack.Logging.Serilog/SerilogExtensions.cs
- src/ServiceStack.Logging.Serilog/SerilogLogger.cs
- src/ServiceStack.Logging.Serilog/ServiceStack.Logging.Serilog.csproj
- src/ServiceStack.Logging.Serilog/packages.config
- tests/ServiceStack.Logging.Tests/ServiceStack.Logging.Tests.csproj
- tests/ServiceStack.Logging.Tests/UnitTests/SerilogLoggerTests.cs
- tests/ServiceStack.Logging.Tests/packages.config
Adding extension methods for leveraging serilog's structured logging capabilties.
Updating serilog version from 2.3 to 2.4
> Serilog enhancements

- src/ServiceStack/Auth/VkAuthProvider.cs
> VKCOM AuthenticateWithAccessToken

- README.md
The link for Fubu MVC was outdated.
> Update link for "similar project"

- src/ServiceStack/Caching/CacheClientWithPrefix.cs
Would be really good to know the Prefix for logging etc.
Simply added a getter to the internal variable
> Exposed Prefix

- tests/ServiceStack.Logging.Tests/UnitTests/NLogTests.cs
Better to listen for actual exceptions, instead of random warnings.
> Minor refactoring of the NLog logger unit test

- src/ServiceStack.Interfaces/DataAnnotations/ReturnAttribute.cs
Removed unused Return attributes.
> Removed unused Return attributes

- src/ServiceStack.Logging.NLog/ServiceStack.Logging.NLog.csproj
> NLog with NetStandard support

- src/ServiceStack/LocalizedStrings.cs
> Error Message Consistency

- CONTRIBUTORS.md
- README.md
... to point to the correct GH profile.
> Update link on README.md and CONTRIBUTORS.md

- src/ServiceStack.RabbitMq/ServiceStack.RabbitMq.Source.csproj
Adds a .Source.csproj for building ServiceStack.RabbitMq for use with OSS projects.
> Adds a .Source.csproj for building ServiceStack.RabbitMq for OSS projects

- src/ServiceStack.RabbitMq/ServiceStack.RabbitMq.Source.csproj
Add net6.0 support to ServiceStack.RabbitMq.Source.csproj
> Adds net6.0 support to ServiceStack.RabbitMq.Source.csproj

- src/ServiceStack/NativeTypes/NativeTypesMetadata.cs
- tests/NorthwindAuto/ui/components/AutoForm.html
Small change to support autoform to pickup properties attributed as required.
> Add metadata for required fields to flow down to AutoForm.html.

- ServiceStack/src/ServiceStack/ServerEventsFeature.cs
I have created an issue [here](https://github.com/ServiceStack/Issues/issues/774)
> Added CancellationToken to ServerEventsFeature.WriteEventAsync

- ServiceStack.OrmLite/src/ServiceStack.OrmLite/Expressions/SqlExpression.cs
- ServiceStack.OrmLite/tests/ServiceStack.OrmLite.MySql.Tests/EnumTests.cs
For detail:
https://github.com/ServiceStack/ServiceStack.OrmLite/pull/667
> Improve enum conversion when indirect member access, such as Sql.TableAlias(), etc.

- ServiceStack/src/ServiceStack.Server/AutoQueryFeature.AutoCrud.cs
The PartialUpdate AutoCrud functions didn't pass through the db parameter to UpdateInternal
> pass through db parameter to update internal

- ServiceStack/src/ServiceStack.Authentication.RavenDb/RavenDbUserAuthRepositoryAsync.cs
- ServiceStack/src/ServiceStack.Authentication.RavenDb/RavenDbUserAuthRepositorySync.cs
This is  IManageApiKeys and IManageApiKeysAsync support for RavenDbUserAuthRepository based on MongoDB.
> IManageApiKeys feature for RavenDb

- ServiceStack/src/ServiceStack/Auth/FacebookAuthProvider.cs
Update/read `ConsumerKey`/`ConsumerSecret` for the `FacebookAuthProvider` so get set details without `appsettings.json`.
> Update/read `ConsumerKey`/`ConsumerSecret` for FacebookAuthProvider

- ServiceStack/src/ServiceStack/modules/locode/components/ModalLookup.html
- ServiceStack/tests/NorthwindAuto/locode/components/ModalLookup.html
Changed based on earlier commit ->
https://github.com/ServiceStack/ServiceStack/commit/56a485fc48b12ebfdfa20b3c3034c544d24c7bad#diff-36de288dbaa0773ca2f5c03f34cce828d99a243fbaa15f911ff96926000138cc
> Add support for modal dialog filtering in locode.

- ServiceStack/src/ServiceStack/CompressResponseAttribute.cs
Fix lose status code when use Compress Response Attribute
> Fix lose status code

- ServiceStack.OrmLite/src/ServiceStack.OrmLite.Sqlite/SqliteExpression.cs
- ServiceStack.OrmLite/tests/ServiceStack.OrmLite.SqliteTests/Expressions/DateTimeFunctionTests.cs
- ServiceStack.OrmLite/tests/ServiceStack.OrmLite.SqliteTests/Expressions/ExpressionsTestBase.cs
- ServiceStack.OrmLite/tests/ServiceStack.OrmLite.SqliteTests/Expressions/TestType.cs
like https://github.com/ServiceStack/ServiceStack.OrmLite/pull/651
> add ToString format paramater support for Sqlite DateTime

- ServiceStack.OrmLite/src/ServiceStack.OrmLite/OrmLiteConfig.cs
- ServiceStack.OrmLite/src/ServiceStack.OrmLite/OrmLiteConnection.cs
Mainly to increase code readability
> Timeout configuration enhancement

- ServiceStack.OrmLite/src/ServiceStack.OrmLite/OrmLiteExecFilter.cs
- ServiceStack.OrmLite/src/ServiceStack.OrmLite/OrmLiteWriteApi.cs
Check the null situation to avoid NRE
Consistent behavior with SetLastCommandText
> Enhance edge case robustness

- ServiceStack/src/ServiceStack/Validation/ValidationFeature.cs
- ServiceStack/tests/ServiceStack.WebHost.Endpoints.Tests/ValidationCustomTests.cs
Fix mixed validators due to modification of main collection during iteration.
> Fix mixed validators due to modification of main collection

- ServiceStack/tests/ServiceStack.Common.Tests/NativeTypesTests.cs
Python type order not resolving correctly. Added tests for AI Server and re-enable native types tests which seemed to have been disabled for NET 8.
> Add failing python. Remove !NETCORE if def for native type tests.
